# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 205)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 67, 17))
        self.label.setObjectName("label")
        self.shorted = QtWidgets.QPushButton(self.centralwidget)
        self.shorted.setGeometry(QtCore.QRect(360, 80, 111, 101))
        self.shorted.setObjectName("shorted")
        self.Url = QtWidgets.QLineEdit(self.centralwidget)
        self.Url.setGeometry(QtCore.QRect(80, 30, 331, 25))
        self.Url.setObjectName("Url")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 131, 16))
        self.label_2.setObjectName("label_2")
        self.shotUrl = QtWidgets.QLabel(self.centralwidget)
        self.shotUrl.setGeometry(QtCore.QRect(140, 90, 211, 17))
        self.shotUrl.setText("")
        self.shotUrl.setObjectName("shotUrl")
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setGeometry(QtCore.QRect(120, 130, 211, 31))
        self.copy.setObjectName("copy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "URL :"))
        self.shorted.setText(_translate("MainWindow", "SHORT"))
        self.label_2.setText(_translate("MainWindow", "Shorten URL :"))
        self.copy.setText(_translate("MainWindow", "COPY"))
